### ISSUE TITLE
系统报错TypeError: got an unexpected keyword argument 'align'

### ISSUE THREAD

**Issue by XiNapoleom** [Asad-Ismail/MoneyPrinterTurbo-Extended#1]
系统报错2025-07-16 21:28:04.330 Uncaught app execution
Traceback (most recent call last):
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 648, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/dou/MoneyPrinterTurbo-Extended/webui/Main.py", line 1216, in <module>
    result = tm.start(task_id=task_id, params=params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dou/MoneyPrinterTurbo-Extended/app/services/task.py", line 326, in start
    final_video_paths, combined_video_paths = generate_final_videos(
                                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dou/MoneyPrinterTurbo-Extended/app/services/task.py", line 215, in generate_final_videos
    video.generate_video(
  File "/Users/dou/MoneyPrinterTurbo-Extended/app/services/video.py", line 969, in generate_video
    clip = create_text_clip(subtitle_item=item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dou/MoneyPrinterTurbo-Extended/app/services/video.py", line 901, in create_text_clip
    _clip = TextClip(
            ^^^^^^^^^
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.11/site-packages/decorator.py", line 234, in fun
    args, kw = fix(args, kw, sig)
               ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.11/site-packages/decorator.py", line 204, in fix
    ba = sig.bind(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.11/inspect.py", line 3195, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.11/inspect.py", line 3184, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'align'

**Comment by Asad-Ismail** [comment]
This was fixed — the align parameter was removed from the TextClip call. Should work fine with moviepy 2.1.2+.
